# Generated by Django 3.1.7 on 2021-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=246, unique=True)),
                ('First_Name', models.CharField(max_length=128)),
                ('Last_Name', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=128)),
                ('uniqueID', models.CharField(max_length=246, unique=True)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
